#!/bin/sh
echo "Content-Type:text/plain"
echo ""
cd /tmp/luci-sessions
if [ $QUERY_STRING = `(date|cut -c12-15;ls /tmp/luci-sessions/)|md5sum|grep -oP "[a-z0-9]*"` ] ; then
	if [ `uci get aria2.@aria2[0].rpc_auth_method` = "user_pass" ] ; then
echo http://\
`uci get aria2.@aria2[0].rpc_user`\
":"\
`uci get aria2.@aria2[0].rpc_passwd`\
"@"\
`uci get network.lan.ipaddr`:`uci get aria2.@aria2[0].rpc_listen_port 2>/dev/null || echo 6800`/jsonrpc
	else
		if [ `uci get aria2.@aria2[0].rpc_auth_method` = "token" ] ; then
echo http://\
"token:"\
`uci get aria2.@aria2[0].rpc_secret`\
"@"\
`uci get network.lan.ipaddr`:`uci get aria2.@aria2[0].rpc_listen_port 2>/dev/null || echo 6800`/jsonrpc
		else
echo http://`uci get network.lan.ipaddr`:`uci get aria2.@aria2[0].rpc_listen_port 2>/dev/null || echo 6800`/jsonrpc
		fi
	fi
fi